#!/bin/sh

BRANCH=${3:-main}
CURRENT_DIR=$PWD
REPOSITORY=$1
TARGET_DIR=$CURRENT_DIR/$2
WORKING_DIR=$(mktemp -d -t dc-XXXXXXXXXX)

# Pull
cd $WORKING_DIR
git clone --single-branch --branch $BRANCH $REPOSITORY .
rm -rf /.git

# Move To Target Directory
cd $CURRENT_DIR
mkdir -p $TARGET_DIR
cp -Rf $WORKING_DIR/* $TARGET_DIR/

# Cleanup
rm -rf $WORKING_DIR
