#!/bin/sh

# Check number of arguments
if [ "$#" -eq 3 ]; then
    BRANCH=$2  
    TARGET_DIR=$PWD/$3  
elif [ "$#" -eq 2 ]; then
    BRANCH="main" 
    TARGET_DIR=$PWD/$2 
else
    echo "Usage: $0 <repository> [branch] <target_directory>"
    exit 1
fi

REPOSITORY=$1
WORKING_DIR=$(mktemp -d -t dc-XXXXXXXXXX)

# Clone
cd $WORKING_DIR
git clone --single-branch --branch $BRANCH $REPOSITORY .
rm -rf /.git

# Move To Target Directory
cd $PWD
mkdir -p $TARGET_DIR
cp -Rf $WORKING_DIR/* $TARGET_DIR/

# Cleanup
rm -rf $WORKING_DIR
